version: '3.7'
networks:
    ev_network:
      driver: bridge

services:
    charging-stations-simulator:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        networks:
            - ev_network
