version: '3.7'
networks:
  ev_network:
    driver: bridge
services:
  charging-stations-simulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        MAX_OLD_SPACE_SIZE: 1024
    networks:
      - ev_network
